// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKDuKhTTWuuX9N9ZXEZ9fARZZK-WH0wc',
    appId: '1:45107367404:web:dd8f198711befad3b704c9',
    messagingSenderId: '45107367404',
    projectId: 'bilgi-yar-47578',
    authDomain: 'bilgi-yar-47578.firebaseapp.com',
    storageBucket: 'bilgi-yar-47578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALoFOp9S4p8WevDslIWeH7n3KdJ7pnEGQ',
    appId: '1:45107367404:android:4273aba6fdaee1b6b704c9',
    messagingSenderId: '45107367404',
    projectId: 'bilgi-yar-47578',
    storageBucket: 'bilgi-yar-47578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkH0hfnNiogJsuQTC_9gRQsrRip7Q5Yts',
    appId: '1:45107367404:ios:124033496a137707b704c9',
    messagingSenderId: '45107367404',
    projectId: 'bilgi-yar-47578',
    storageBucket: 'bilgi-yar-47578.appspot.com',
    iosBundleId: 'com.example.bilgiBarismasi',
  );
}
